// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package infras

import (
	"github.com/GoldenOwlAsia/golang-api-template/handlers"
	"github.com/GoldenOwlAsia/golang-api-template/services"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitUserAPI(db *gorm.DB) handlers.UserHandler {
	userService := services.NewUserService(db)
	userHandler := handlers.NewUserHandler(userService)
	return userHandler
}

func InitArticleAPI(db *gorm.DB) handlers.ArticleHandler {
	articleService := services.NewArticleService(db)
	articleHandler := handlers.NewArticleHandler(articleService)
	return articleHandler
}
