// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package infras

import (
	"api/handler/api/v1"
	"api/repository"
	"api/services"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitUserAPI(db *gorm.DB) v1.UserHandler {
	userRepository := repository.NewUserRepository(db)
	userService := services.NewUserService(userRepository)
	userHandler := v1.NewUserHandler(userService)
	return userHandler
}
