// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package infras

import (
	"github.com/GoldenOwlAsia/golang-api-template/api/v1"
	"github.com/GoldenOwlAsia/golang-api-template/repository"
	"github.com/GoldenOwlAsia/golang-api-template/services"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitUserAPI(db *gorm.DB) v1.UserHandler {
	userRepository := repository.NewUserRepository(db)
	userService := services.NewUserService(userRepository)
	userHandler := v1.NewUserHandler(userService)
	return userHandler
}

func InitArticleAPI(db *gorm.DB) v1.ArticleHandler {
	articleHandler := v1.NewArticleHandler(db)
	return articleHandler
}
