version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    container_name: web-postgres
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    container_name: web
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - default
    restart: always

volumes:
  data:
