basePath: /
definitions:
  requests.UserLoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  responses.UserLoginResponse:
    properties:
      access_token:
        type: string
      id:
        type: string
      refresh_token:
        type: string
    type: object
  utils.ResponseFailed:
    properties:
      code:
        type: integer
      message:
        type: string
      status_code:
        type: string
    type: object
  utils.ResponseSuccess:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
      status_code:
        type: string
    type: object
info:
  contact:
    email: hello@goldenowl.asia
    name: goldenowl.asia
  description: This API is for GoldenOwl API application
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: GoldenOwl Gin API
  version: 1.0.0
paths:
  /api/v1/user/login:
    post:
      consumes:
      - application/json
      description: login by username & password
      parameters:
      - description: body params
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/requests.UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.ResponseSuccess'
            - properties:
                Data:
                  $ref: '#/definitions/responses.UserLoginResponse'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.ResponseFailed'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/utils.ResponseFailed'
      summary: Login user to system
      tags:
      - users
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
